#line 2 "scanner.yy.c"

#line 4 "scanner.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 39
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern yy_size_t yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	yy_size_t yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static yy_size_t yy_n_chars;		/* number of characters read into yy_ch_buf */
yy_size_t yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,yy_size_t len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() 1
#define YY_SKIP_YYWRAP

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 132
#define YY_END_OF_BUFFER 133
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[313] =
    {   0,
        0,    0,    0,    0,    0,    0,  133,  131,  130,  129,
      116,  131,  111,   76,   82,   83,   93,   75,  109,   84,
      118,  102,  128,  128,  119,  110,   89,  107,   98,  122,
       91,   92,   94,   71,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  100,   85,  101,    5,    4,    5,   74,   73,   72,
      130,   81,    0,   70,    0,  113,   79,   78,  120,   95,
      106,   77,  115,   86,    0,  125,    2,    1,  104,    0,
      128,  127,    0,  124,  108,   97,  103,   90,   80,   99,
      112,  122,   96,  122,  122,  122,  122,  122,  122,  122,

      122,  122,  122,  122,  122,  122,  122,  122,   13,   23,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,   87,
       88,    3,  121,  117,  125,  125,  125,  123,    1,  127,
      126,  105,  114,  122,  122,  122,  122,   56,  122,  122,
      122,  122,  122,  122,  122,  122,  122,  122,  122,  122,
       27,  122,  122,  122,  122,   38,  122,   62,  122,   14,
       64,   54,  122,  122,  122,  122,  122,  122,  122,  122,
      122,  122,  122,  122,  122,  122,   30,  125,  122,   31,
      122,   32,   11,   16,  122,  122,  122,  122,   59,  122,

      122,  122,   17,  122,  122,  122,  122,    8,   18,   61,
      122,  122,  122,  122,   39,  122,   53,   63,  122,  122,
      122,  122,   68,  122,  122,   43,  122,  122,  122,  122,
       51,   25,   45,  122,    6,   57,  122,   21,  122,  122,
       12,  122,   35,  122,   52,  122,  122,   40,   41,   42,
      122,  122,   65,   66,   24,  122,  122,  122,  122,  122,
      122,  122,  122,  122,   46,  122,   55,  122,  122,  122,
       60,  122,  122,  122,   28,  122,  122,  122,  122,   29,
       10,   44,   15,   20,   47,   48,   49,  122,   58,  122,
        7,  122,   36,   37,  122,   19,   67,   69,   50,  122,

      122,   26,  122,  122,  122,   33,  122,    9,   34,  122,
       22,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    1,    1,    6,    7,    1,    8,
        9,   10,   11,   12,   13,   14,   15,   16,   17,   18,
       19,   20,   21,   22,   21,   23,   24,   25,   26,   27,
       28,   29,    1,    1,   30,   30,   30,   30,   31,   30,
       32,   32,   32,   32,   32,   32,   32,   32,   32,   32,
       32,   32,   32,   32,   32,   32,   32,   33,   32,   32,
       34,   35,   36,   37,   32,   38,   39,   40,   41,   42,

       43,   44,   45,   46,   47,   32,   48,   49,   50,   51,
       52,   53,   32,   54,   55,   56,   57,   58,   59,   60,
       61,   32,   62,   63,   64,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[65] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    1,    1,    1,
        3,    1,    3,    4,    1,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    1,    1,    1,    1,    1,    6,
        7,    8,    8,    1,    1,    1,    1,    1,    6,    6,
        6,    6,    7,    6,    8,    8,    9,    8,    8,    8,
        8,    8,    8,    8,    8,    8,    8,    8,    8,    8,
        8,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[324] =
    {   0,
        0,    0,   62,   63,   64,   65,  427,  428,   69,  428,
      398,   64,  397,   63,  428,  428,  396,   64,  428,   61,
      409,   66,   91,   69,  394,  428,   69,  393,   49,    0,
      428,  428,  392,  428,  366,   32,   49,  375,   31,   78,
      365,   81,  373,  376,   75,   67,   80,   83,   75,  367,
      374,  428,   92,  428,  428,  428,  397,  428,  428,  428,
      126,  428,  129,  428,  408,  428,  428,  428,  382,  428,
      428,  428,  428,  428,  395,  132,  428,    0,  428,  149,
      127,  130,    0,  428,  428,  428,  380,  428,  428,  428,
      379,    0,  428,  353,  353,  361,  347,   93,  363,  349,

       99,  113,  345,  345,  349,  345,  342,  344,  338,    0,
      137,  337,  336,  340,  130,  331,  340,  140,  341,  336,
      141,  335,  336,  330,  336,  325,  328,  329,  325,  428,
      428,  428,  428,  428,  145,  173,  174,  428,    0,  175,
        0,  428,  428,  335,  328,  337,  332,    0,  331,  322,
      317,  318,  104,  309,  157,  326,  325,  315,  139,  327,
        0,  324,  312,  318,  310,  184,  322,    0,  317,    0,
        0,    0,  311,  311,  306,  311,  306,  302,  296,  309,
      308,  155,  294,  306,  305,  291,    0,  182,  295,    0,
      297,    0,    0,    0,  301,  294,  286,  294,    0,  283,

      285,  282,    0,  283,  280,  292,  278,    0,    0,    0,
      279,  310,  313,  310,    0,  275,    0,    0,  289,  286,
      270,  282,    0,  266,  269,    0,  281,  270,  279,  278,
        0,    0,  191,  276,    0,    0,  274,    0,  264,  265,
        0,  270,    0,  265,    0,   68,  249,    0,    0,    0,
      260,  258,    0,  244,    0,  247,  237,  230,  233,  221,
      230,  221,  224,  221,    0,  184,    0,  179,  181,  181,
        0,  182,  217,  214,    0,  194,  189,  180,  176,    0,
        0,    0,    0,    0,    0,    0,    0,  174,  201,  183,
        0,  173,    0,    0,  183,    0,    0,    0,    0,  201,

      195,    0,  154,  166,  124,    0,   95,    0,    0,   33,
        0,  428,  244,  253,  262,  268,  270,  275,  282,  291,
      297,  302,  307
    } ;

static yyconst flex_int16_t yy_def[324] =
    {   0,
      312,    1,  313,  313,  314,  314,  312,  312,  312,  312,
      312,  315,  312,  312,  312,  312,  312,  312,  312,  312,
      316,  312,  312,  317,  312,  312,  312,  312,  312,  318,
      312,  312,  312,  312,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  315,  312,  315,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  319,  312,  320,  312,  312,
      317,  321,  322,  312,  312,  312,  312,  312,  312,  312,
      312,  318,  312,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  312,
      312,  312,  312,  312,  323,  319,  323,  312,  320,  321,
      322,  312,  312,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  323,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,

      318,  318,  318,  318,  318,  318,  318,  318,  318,  318,
      318,    0,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312
    } ;

static yyconst flex_int16_t yy_nxt[493] =
    {   0,
        8,    9,   10,   11,   12,   13,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   24,   24,   24,
       24,   24,   24,   24,   25,   26,   27,   28,   29,   30,
       30,   30,   30,   31,    9,   32,   33,   34,   35,   36,
       37,   38,   39,   40,   41,   30,   42,   30,   43,   44,
       45,   30,   46,   47,   48,   49,   50,   51,   30,   30,
       30,   52,   53,   54,   56,   56,   59,   59,   64,   67,
       61,   57,   57,   73,   71,   77,   90,   91,  311,  103,
       78,   86,   80,   95,  104,   96,  273,   98,   74,  274,
       68,   72,   97,   79,   99,   87,   88,  100,   65,   69,

      101,   60,   60,   61,   80,  118,   81,   82,   82,   82,
       82,   82,   82,   81,   81,   84,  105,  116,  120,  130,
      119,  117,  121,   83,  110,  123,  106,   61,  126,  107,
      111,  112,  113,   64,  108,  127,  122,   84,  124,  310,
       80,  125,  135,   80,  135,  148,  309,  149,  152,  153,
       83,  154,   81,   81,  131,  135,  155,  135,  197,  198,
       61,  156,  137,   65,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   84,  137,  164,   84,  169,  138,  177,
      173,  178,  170,  135,  135,  135,  135,  205,   80,  165,
      174,  138,  312,  206,  312,  200,  179,   81,   81,  201,

      212,  228,  213,  137,  137,  214,  215,  262,  308,  263,
      307,  229,  264,  265,  306,  137,  137,  300,  305,  138,
      138,   84,  301,  304,  303,  302,  216,  299,  138,  298,
      297,  296,  295,  294,  293,  292,  291,  290,  289,  288,
      287,  286,  285,  266,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   58,   58,   58,   58,   58,   58,   58,
       58,   58,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   76,   76,   81,   81,  284,  283,  282,   81,   92,
       92,   92,   92,   92,  136,  281,  136,  280,  136,  279,
      136,  139,  278,  139,  139,  139,  139,  139,  139,  139,

      140,  140,  277,  276,  275,  140,  141,  141,  141,  188,
      272,  188,  271,  270,  269,  188,  268,  267,  261,  260,
      259,  258,  257,  256,  255,  254,  253,  252,  251,  250,
      249,  248,  247,  246,  245,  244,  243,  242,  241,  240,
      239,  238,  237,  236,  235,  234,  233,  232,  231,  230,
      227,  226,  225,  224,  223,  222,  221,  220,  219,  218,
      217,  211,  210,  209,  208,  207,  204,  203,  202,  199,
      196,  195,  194,  193,  192,  191,  190,  189,  187,  186,
      185,  184,  183,  182,  181,  180,  176,  175,  172,  171,
      168,  167,  166,  163,  162,  161,  160,  159,  158,  157,

      151,  150,  147,  146,  145,  144,  143,  142,  134,  133,
      312,  132,  129,  128,  115,  114,  109,  102,   94,   93,
       89,   85,   75,   70,   66,   62,  312,    7,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312

    } ;

static yyconst flex_int16_t yy_chk[493] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    3,    4,    5,    6,   12,   14,
        9,    3,    4,   20,   18,   22,   29,   29,  310,   39,
       22,   27,   24,   36,   39,   36,  246,   37,   20,  246,
       14,   18,   36,   22,   37,   27,   27,   37,   12,   14,

       37,    5,    6,    9,   23,   46,   23,   23,   23,   23,
       23,   23,   23,   23,   23,   24,   40,   45,   47,   53,
       46,   45,   47,   23,   42,   48,   40,   61,   49,   40,
       42,   42,   42,   63,   40,   49,   47,   23,   48,  307,
       81,   48,   76,   82,   76,   98,  305,   98,  101,  101,
       23,  101,   82,   82,   53,  135,  102,  135,  153,  153,
       61,  102,   76,   63,   80,   80,   80,   80,   80,   80,
       80,   80,   80,   81,   76,  111,   82,  115,   76,  121,
      118,  121,  115,  136,  137,  136,  137,  159,  140,  111,
      118,  135,  188,  159,  188,  155,  121,  140,  140,  155,

      166,  182,  166,  136,  137,  166,  166,  233,  304,  233,
      303,  182,  233,  233,  301,  136,  137,  289,  300,  136,
      137,  140,  289,  295,  292,  290,  166,  288,  188,  279,
      278,  277,  276,  274,  273,  272,  270,  269,  268,  266,
      264,  263,  262,  233,  313,  313,  313,  313,  313,  313,
      313,  313,  313,  314,  314,  314,  314,  314,  314,  314,
      314,  314,  315,  315,  315,  315,  315,  315,  315,  315,
      315,  316,  316,  317,  317,  261,  260,  259,  317,  318,
      318,  318,  318,  318,  319,  258,  319,  257,  319,  256,
      319,  320,  254,  320,  320,  320,  320,  320,  320,  320,

      321,  321,  252,  251,  247,  321,  322,  322,  322,  323,
      244,  323,  242,  240,  239,  323,  237,  234,  230,  229,
      228,  227,  225,  224,  222,  221,  220,  219,  216,  214,
      213,  212,  211,  207,  206,  205,  204,  202,  201,  200,
      198,  197,  196,  195,  191,  189,  186,  185,  184,  183,
      181,  180,  179,  178,  177,  176,  175,  174,  173,  169,
      167,  165,  164,  163,  162,  160,  158,  157,  156,  154,
      152,  151,  150,  149,  147,  146,  145,  144,  129,  128,
      127,  126,  125,  124,  123,  122,  120,  119,  117,  116,
      114,  113,  112,  109,  108,  107,  106,  105,  104,  103,

      100,   99,   97,   96,   95,   94,   91,   87,   75,   69,
       65,   57,   51,   50,   44,   43,   41,   38,   35,   33,
       28,   25,   21,   17,   13,   11,    7,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312,  312,  312,  312,  312,  312,  312,  312,  312,
      312,  312

    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "scanner.l"
#line 6 "scanner.l"
	#include <stdio.h>
	#include <math.h>
	#include "parser.h"
	int line = 1;


#line 680 "scanner.yy.c"

#define INITIAL 0
#define MULTILINE_COMMENT 1
#define MULTILINE_STRING_LITERAL 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

yy_size_t yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		size_t n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	{
#line 19 "scanner.l"



#line 895 "scanner.yy.c"

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 313 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_current_state != 312 );
		yy_cp = (yy_last_accepting_cpos);
		yy_current_state = (yy_last_accepting_state);

yy_find_action:
		yy_act = yy_accept[yy_current_state];

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 22 "scanner.l"
{}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 24 "scanner.l"
{BEGIN(MULTILINE_COMMENT);}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 25 "scanner.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 26 "scanner.l"
{++line; } 
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 27 "scanner.l"
{}   
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 30 "scanner.l"
{return BREAK;}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 31 "scanner.l"
{return DEFAULT;}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 32 "scanner.l"
{return FUNC;}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 33 "scanner.l"
{return INTERFACE;}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 34 "scanner.l"
{return SELECT;}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 35 "scanner.l"
{return CASE;}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 36 "scanner.l"
{return DEFER;}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 37 "scanner.l"
{return GOROUTINE;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 38 "scanner.l"
{return MAP;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 39 "scanner.l"
{return STRUCT;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 40 "scanner.l"
{return CHANNEL;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 41 "scanner.l"
{return ELSE;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 42 "scanner.l"
{return GOTO;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 43 "scanner.l"
{return PACKAGE;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 44 "scanner.l"
{return SWITCH;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 45 "scanner.l"
{return CONST;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 46 "scanner.l"
{return FALLTHROUGH;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 47 "scanner.l"
{return IF;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 48 "scanner.l"
{return RANGE;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 49 "scanner.l"
{return TYPE;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 50 "scanner.l"
{return CONTINUE;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 51 "scanner.l"
{return FOR;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 52 "scanner.l"
{return IMPORT;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 53 "scanner.l"
{return RETURN;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 54 "scanner.l"
{return VAR;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 56 "scanner.l"
{return BOOL;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 57 "scanner.l"
{return BYTE_TYPE;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 58 "scanner.l"
{return COMPLEX64_TYPE;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 59 "scanner.l"
{return COMPLEX128_TYPE;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 60 "scanner.l"
{return ERROR_TYPE;} 
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 61 "scanner.l"
{return FLOAT32_TYPE;}
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 62 "scanner.l"
{return FLOAT64_TYPE;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 63 "scanner.l"
{return INT_TYPE;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 64 "scanner.l"
{return INT8_TYPE;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 65 "scanner.l"
{return INT16_TYPE;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 66 "scanner.l"
{return INT32_TYPE;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 67 "scanner.l"
{return INT64_TYPE;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 68 "scanner.l"
{return RUNE_TYPE;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 69 "scanner.l"
{return STRING_TYPE;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 70 "scanner.l"
{return UINT_TYPE;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "scanner.l"
{return UINT8_TYPE;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 72 "scanner.l"
{return UINT16_TYPE;}
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 73 "scanner.l"
{return UINT32_TYPE;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "scanner.l"
{return UINT64_TYPE;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "scanner.l"
{return UINTPTR_TYPE;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 77 "scanner.l"
{return TRUE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 78 "scanner.l"
{return FALSE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 79 "scanner.l"
{return IOTA;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 80 "scanner.l"
{return NIL;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 82 "scanner.l"
{return APPEND_FUNC;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 83 "scanner.l"
{return CAP_FUNC;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 84 "scanner.l"
{return CLOSE_FUNC;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 85 "scanner.l"
{return COMPLEX_FUNC;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 86 "scanner.l"
{return COPY_FUNC;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 87 "scanner.l"
{return DELETE_FUNC;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 88 "scanner.l"
{return IMAG_FUNC;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 89 "scanner.l"
{return LEN_FUNC;}	
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 90 "scanner.l"
{return MAKE_FUNC;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 91 "scanner.l"
{return NEW_FUNC;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 92 "scanner.l"
{return PANIC_FUNC;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 93 "scanner.l"
{return PRINT_FUNC;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 94 "scanner.l"
{return PRINTLN_FUNC;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 95 "scanner.l"
{return REAL_FUNC;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 96 "scanner.l"
{return RECOVER_FUNC;}
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 98 "scanner.l"
{return STRING_LITERAL;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 100 "scanner.l"
{BEGIN(MULTILINE_STRING_LITERAL);}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 101 "scanner.l"
{BEGIN(INITIAL);}
	YY_BREAK
case 73:
/* rule 73 can match eol */
YY_RULE_SETUP
#line 102 "scanner.l"
{ ++line; } 
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 103 "scanner.l"
{return MULTILINE_STRING_LITERAL;}   
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 105 "scanner.l"
{return PLUS_OP;}  
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 106 "scanner.l"
{return AMPERSAND_OP;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 107 "scanner.l"
{return PLUS_ASSIGN_OP;}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 108 "scanner.l"
{return BITWISE_AND_ASSIGN_OP;}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 109 "scanner.l"
{return AND_OP;}
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 110 "scanner.l"
{return EQU_OP;}
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 111 "scanner.l"
{return NOT_EQU_OP;}
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 112 "scanner.l"
{return LEFT_PAREN;}
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 113 "scanner.l"
{return RIGHT_PAREN;}
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 114 "scanner.l"
{return MINUS_OP;}
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 115 "scanner.l"
{return BITWISE_OR_OP;}
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 116 "scanner.l"
{return MINUS_ASSIGN_OP;}
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 117 "scanner.l"
{return BITWISE_OR_ASSIGN_OP;}
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 118 "scanner.l"
{return OR_OP;}
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 119 "scanner.l"
{return LOWER_OP;}
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 120 "scanner.l"
{return LOWER_OR_EQU_OP;}
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 121 "scanner.l"
{return LEFT_SQUARE_BRACKET;}
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 122 "scanner.l"
{return RIGHT_SQUARE_BRACKET;}
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 123 "scanner.l"
{return ASTERISK_OP;}
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 124 "scanner.l"
{return BITWISE_XOR_OP;}
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 125 "scanner.l"
{return MUL_ASSIGN_OP;}
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 126 "scanner.l"
{return BITWISE_XOR_ASSIGN_OP;}
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 127 "scanner.l"
{return SEND_RECIEVE_OP;}
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 128 "scanner.l"
{return HIGHER_OP;}
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 129 "scanner.l"
{return HIGHER_OR_EQU_OP;}
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 130 "scanner.l"
{return LEFT_CURLY_BRACE;}
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 131 "scanner.l"
{return RIGHT_CURLY_BRACE;}
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 132 "scanner.l"
{return DIV_OP;}
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 133 "scanner.l"
{return LEFT_SHIFT_OP;}
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 134 "scanner.l"
{return DIV_ASSIGN_OP;}
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 135 "scanner.l"
{return LEFT_SHIFT_ASSIGN_OP;}
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 136 "scanner.l"
{return INCREMENT_OP;}
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 137 "scanner.l"
{return ASSIGN_OP;}
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 138 "scanner.l"
{return SHORTHAND_ASSIGN_OP;}
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 139 "scanner.l"
{return COMMA;}
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 140 "scanner.l"
{return SEMICOLON;}
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 141 "scanner.l"
{return MOD_OP;}
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 142 "scanner.l"
{return RIGHT_SHIFT_OP;}
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 143 "scanner.l"
{return MOD_ASSIGN_OP;}
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 144 "scanner.l"
{return RIGHT_SHIFT_ASSIGN_OP;}
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 145 "scanner.l"
{return DECREMENT_OP;}
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 146 "scanner.l"
{return NOT_OP;}
	YY_BREAK
case 117:
YY_RULE_SETUP
#line 147 "scanner.l"
{return ELIPSIS_OP;}
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 148 "scanner.l"
{return DOT_OP;}
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 149 "scanner.l"
{return COLON_OP;}
	YY_BREAK
case 120:
YY_RULE_SETUP
#line 150 "scanner.l"
{return AND_NOT_BITWISE_OP;}
	YY_BREAK
case 121:
YY_RULE_SETUP
#line 151 "scanner.l"
{return AND_NOT_BITWISE_ASSIGN_OP;}
	YY_BREAK
case 122:
YY_RULE_SETUP
#line 154 "scanner.l"
{return IDENTIFIER;}
	YY_BREAK
case 123:
YY_RULE_SETUP
#line 155 "scanner.l"
{return COMPLEX_FLOAT_NUMBER;}
	YY_BREAK
case 124:
YY_RULE_SETUP
#line 156 "scanner.l"
{return COMPLEX_DECIMAL_NUMBER;}
	YY_BREAK
case 125:
YY_RULE_SETUP
#line 157 "scanner.l"
{return FLOAT_NUMBER;}
	YY_BREAK
case 126:
YY_RULE_SETUP
#line 158 "scanner.l"
{return HEXADECIMAL_NUMBER;}
	YY_BREAK
case 127:
YY_RULE_SETUP
#line 159 "scanner.l"
{return OCTAL_NUMBER;}
	YY_BREAK
case 128:
YY_RULE_SETUP
#line 160 "scanner.l"
{return DECIMAL_NUMBER;}
	YY_BREAK
case 129:
/* rule 129 can match eol */
YY_RULE_SETUP
#line 162 "scanner.l"
{line++;}
	YY_BREAK
case 130:
YY_RULE_SETUP
#line 163 "scanner.l"
{}
	YY_BREAK
case 131:
YY_RULE_SETUP
#line 164 "scanner.l"
{printf("->unknown<-: \"%s\", line: %i\n", yytext, line);}
	YY_BREAK
case 132:
YY_RULE_SETUP
#line 166 "scanner.l"
ECHO;
	YY_BREAK
#line 1612 "scanner.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(MULTILINE_COMMENT):
case YY_STATE_EOF(MULTILINE_STRING_LITERAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_last_accepting_cpos);
				yy_current_state = (yy_last_accepting_state);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			yy_size_t num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				yy_size_t new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 313 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 313 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 312);

		return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register yy_size_t number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			yy_size_t offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, yy_size_t  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	yy_size_t i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
yy_size_t yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 166 "scanner.l"



int octal_decimal(int n) 
{
    int decimal=0, i=0, rem;
    while (n!=0)
    {
        rem = n%10;
        n/=10;
        decimal += rem*pow(8,i);
        ++i;
    }
    return decimal;
}

long hex_decimal(char hex[])
{
    char *hexstr;
    int length = 0;
    const int base = 16; // Base of Hexadecimal Number
    unsigned long decnum = 0;
    int i;
    // Find length of Hexadecimal Number
    for (hexstr = hex; *hexstr != '\0'; hexstr++)
    {
		length++;
    }
    // Find Hexadecimal Number
    hexstr = hex;
    for (i = 0; *hexstr != '\0' && i < length; i++, hexstr++)
    {
		// Compare *hexstr with ASCII values
		if (*hexstr >= 48 && *hexstr <= 57)   // is *hexstr Between 0-9
		{
			decnum += (((int)(*hexstr)) - 48) * pow(base, length - i - 1);
		}
		else if ((*hexstr >= 65 && *hexstr <= 70))   // is *hexstr Between A-F
		{
			decnum += (((int)(*hexstr)) - 55) * pow(base, length - i - 1);
		}
		else if (*hexstr >= 97 && *hexstr <= 102)   // is *hexstr Between a-f
		{
			decnum += (((int)(*hexstr)) - 87) * pow(base, length - i - 1);
		}
    }
    return decnum;
}
