#ifndef _TREE_H_
#define _TREE_H_

enum ExpressionType {
	AND, OR, EQU, NE, GT, GTE, LT, LTE, PLUS, MINUS, MULTIPLE, DIVIDE, MODULE,  
	STRING, FLOAT_NUMBER, DECIMAL_NUMBER, 
	IDENTIFIER, 
	ARRAY_ACCESS, 
	FUNCTION_CALL, 
	EXPRESSION_IN_PARENTHESES, 
	UNARY_PLUS, 
	UNARY_MINUS, 
	UNARY_NOT
};

enum StatementType {
	SIMPLE_STATEMENT,
	VAR_DECLARE, 
	CONST_DECLARE, 
	RETURN_STATEMENT, 
	BREAK, 
	CONTINUE, 
	BLOCK, 
	IF_STATEMENT, 
	SWITCH_STATEMENT, 
	FOR_STATEMENT
};

#endif// _TREE_H_